version: '3.8'

x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-09-22T00-33-43Z
  command: server --console-address ":${MINIO_CONSOLE_PORT}" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  minio1:
    <<: *minio-common
    container_name: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

  minio2:
    <<: *minio-common
    container_name: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

  minio3:
    <<: *minio-common
    container_name: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

  minio4:
    <<: *minio-common
    container_name: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

  nginx:
    image: nginx:1.24.0-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
